#!/bin/bash
xrdb  $HOME/.Xresources
/usr/lib/xfce4/notifyd/xfce4-notifyd &
# Start GNOME Keyring
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export SSH_AUTH_SOCK
export GPG_AGENT_INFO
export GNOME_KEYRING_CONTROL
export GNOME_KEYRING_PID

rotatingwallpaper &
SpiderOak &
xscreensaver &
xcompmgr -c -C -t-5 -l-5 -r4.2 -o.55 &
exec xmonad
