#!/bin/bash

#Increase 2D pixmap performance for firefox
nvidia-settings -a InitialPixmapPlacement=2
xrdb  $HOME/.Xresources
/usr/lib/xfce4/notifyd/xfce4-notifyd &
# Start GNOME Keyring
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export SSH_AUTH_SOCK
export GPG_AGENT_INFO
export GNOME_KEYRING_CONTROL
export GNOME_KEYRING_PID

rotatingwallpaper &
SpiderOak &
trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 10 --transparent true --tint 0x191970 --height 12 &
xscreensaver -no-splash &
xcompmgr -f -F -D4 &
nm-applet &
exec xmonad
