#!/bin/bash

#Increase 2D pixmap performance for firefox
nvidia-settings -a InitialPixmapPlacement=2
xsetroot -cursor_name left_ptr
xrdb  $HOME/.Xresources
/usr/lib/xfce4/notifyd/xfce4-notifyd &
# Start GNOME Keyring
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export SSH_AUTH_SOCK
export GPG_AGENT_INFO
export GNOME_KEYRING_CONTROL
export GNOME_KEYRING_PID

rotatingwallpaper &
SpiderOak &
xscreensaver -no-splash &
# xcompmgr -f -F -D4 &
nm-applet &
exec xmonad
